### ISSUE TITLE
Publish on the public store

### ISSUE THREAD

**Issue by jocado** [snapcore/nvidia-core22#1]
Hi @xnox  - this snap doesn't seem to be available on the public store.  I would like to validate the nvidia-assemble is working on UC22.

Should it be published, or is it planned to be  ?

**Comment by xnox** [comment]
@jocado this snap has always been in the public store, open to download and install by anybody.

What and how are you doing things, for me to reproduce the issues you are experiencing with this snap?

https://snapcraft.io/nvidia-core22 shows that there are a few users of this snap

**Comment by jocado** [comment]
Sorry @xnox - too tabs windows open, I meant to create this issue against graphics-core22-samples.
